#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 1
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 16
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 21

enum {
  sym_identifier = 1,
  sym_trim = 2,
  anon_sym_SQUOTE = 3,
  aux_sym_string_token1 = 4,
  anon_sym_DQUOTE = 5,
  aux_sym_string_token2 = 6,
  aux_sym_number_token1 = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_assign = 10,
  anon_sym_EQ = 11,
  anon_sym_DOT = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  anon_sym_EQ_EQ = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_GT = 17,
  anon_sym_LT = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_LT_EQ = 20,
  anon_sym_contains = 21,
  anon_sym_or = 22,
  anon_sym_and = 23,
  anon_sym_PIPE = 24,
  anon_sym_COLON = 25,
  anon_sym_COMMA = 26,
  anon_sym_include = 27,
  anon_sym_render = 28,
  anon_sym_unless = 29,
  anon_sym_endunless = 30,
  anon_sym_if = 31,
  anon_sym_endif = 32,
  anon_sym_elseif = 33,
  anon_sym_else = 34,
  sym_comment = 35,
  sym_program = 36,
  sym__statement = 37,
  sym__literal = 38,
  sym_string = 39,
  sym_number = 40,
  sym_boolean = 41,
  sym_assignment = 42,
  sym__control_flow = 43,
  sym__expression = 44,
  sym_access = 45,
  sym_comparision_operator = 46,
  sym_logical_operator = 47,
  sym_filter = 48,
  sym_argument_list = 49,
  sym_argument = 50,
  sym_include_expression = 51,
  sym_render_expression = 52,
  sym_binary_expression = 53,
  sym_unless_tag = 54,
  sym_if_tag = 55,
  sym_elseif_tag = 56,
  sym_else_tag = 57,
  aux_sym_program_repeat1 = 58,
  aux_sym_access_repeat1 = 59,
  aux_sym_argument_list_repeat1 = 60,
  aux_sym_if_tag_repeat1 = 61,
  alias_sym_block = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_trim] = "trim",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [aux_sym_number_token1] = "number_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_assign] = "assign",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_contains] = "contains",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_PIPE] = "|",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_include] = "include",
  [anon_sym_render] = "render",
  [anon_sym_unless] = "unless",
  [anon_sym_endunless] = "endunless",
  [anon_sym_if] = "if",
  [anon_sym_endif] = "endif",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [sym_comment] = "comment",
  [sym_program] = "program",
  [sym__statement] = "_statement",
  [sym__literal] = "_literal",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_assignment] = "assignment",
  [sym__control_flow] = "_control_flow",
  [sym__expression] = "_expression",
  [sym_access] = "access",
  [sym_comparision_operator] = "comparision_operator",
  [sym_logical_operator] = "logical_operator",
  [sym_filter] = "filter",
  [sym_argument_list] = "argument_list",
  [sym_argument] = "argument",
  [sym_include_expression] = "include_expression",
  [sym_render_expression] = "render_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unless_tag] = "unless_tag",
  [sym_if_tag] = "if_tag",
  [sym_elseif_tag] = "elseif_tag",
  [sym_else_tag] = "else_tag",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_access_repeat1] = "access_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_if_tag_repeat1] = "if_tag_repeat1",
  [alias_sym_block] = "block",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_trim] = sym_trim,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_assign] = anon_sym_assign,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_contains] = anon_sym_contains,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_render] = anon_sym_render,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_endunless] = anon_sym_endunless,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [sym_comment] = sym_comment,
  [sym_program] = sym_program,
  [sym__statement] = sym__statement,
  [sym__literal] = sym__literal,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_assignment] = sym_assignment,
  [sym__control_flow] = sym__control_flow,
  [sym__expression] = sym__expression,
  [sym_access] = sym_access,
  [sym_comparision_operator] = sym_comparision_operator,
  [sym_logical_operator] = sym_logical_operator,
  [sym_filter] = sym_filter,
  [sym_argument_list] = sym_argument_list,
  [sym_argument] = sym_argument,
  [sym_include_expression] = sym_include_expression,
  [sym_render_expression] = sym_render_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unless_tag] = sym_unless_tag,
  [sym_if_tag] = sym_if_tag,
  [sym_elseif_tag] = sym_elseif_tag,
  [sym_else_tag] = sym_else_tag,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_access_repeat1] = aux_sym_access_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_if_tag_repeat1] = aux_sym_if_tag_repeat1,
  [alias_sym_block] = alias_sym_block,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_trim] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assign] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contains] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_render] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endunless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__control_flow] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_access] = {
    .visible = true,
    .named = true,
  },
  [sym_comparision_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_include_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_render_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_if_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_else_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_access_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_block] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_alternatives = 1,
  field_body = 2,
  field_condition = 3,
  field_consequence = 4,
  field_field = 5,
  field_include = 6,
  field_included_file = 7,
  field_key = 8,
  field_left = 9,
  field_name = 10,
  field_operand = 11,
  field_operator = 12,
  field_render = 13,
  field_rendered_file = 14,
  field_right = 15,
  field_value = 16,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternatives] = "alternatives",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_field] = "field",
  [field_include] = "include",
  [field_included_file] = "included_file",
  [field_key] = "key",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_render] = "render",
  [field_rendered_file] = "rendered_file",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 1},
  [13] = {.index = 21, .length = 2},
  [14] = {.index = 23, .length = 2},
  [15] = {.index = 25, .length = 2},
  [16] = {.index = 27, .length = 3},
  [17] = {.index = 30, .length = 3},
  [18] = {.index = 33, .length = 3},
  [19] = {.index = 36, .length = 4},
  [20] = {.index = 40, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_field, 1, .inherited = true},
    {field_operand, 0},
  [2] =
    {field_include, 0},
    {field_included_file, 1},
  [4] =
    {field_render, 0},
    {field_rendered_file, 1},
  [6] =
    {field_field, 1},
  [7] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
  [9] =
    {field_condition, 1},
  [10] =
    {field_alternatives, 0},
  [11] =
    {field_body, 0},
    {field_name, 2},
  [13] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [16] =
    {field_left, 1},
    {field_right, 3},
  [18] =
    {field_condition, 1},
    {field_consequence, 2},
  [20] =
    {field_consequence, 1},
  [21] =
    {field_alternatives, 2},
    {field_condition, 1},
  [23] =
    {field_alternatives, 2, .inherited = true},
    {field_condition, 1},
  [25] =
    {field_alternatives, 0, .inherited = true},
    {field_alternatives, 1, .inherited = true},
  [27] =
    {field_alternatives, 3},
    {field_condition, 1},
    {field_consequence, 2},
  [30] =
    {field_alternatives, 3, .inherited = true},
    {field_condition, 1},
    {field_consequence, 2},
  [33] =
    {field_alternatives, 2, .inherited = true},
    {field_alternatives, 3},
    {field_condition, 1},
  [36] =
    {field_alternatives, 3, .inherited = true},
    {field_alternatives, 4},
    {field_condition, 1},
    {field_consequence, 2},
  [40] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [11] = {
    [2] = alias_sym_block,
  },
  [12] = {
    [1] = alias_sym_block,
  },
  [16] = {
    [2] = alias_sym_block,
  },
  [17] = {
    [2] = alias_sym_block,
  },
  [19] = {
    [2] = alias_sym_block,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_program_repeat1, 2,
    aux_sym_program_repeat1,
    alias_sym_block,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '!') ADVANCE(2);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == ',') ADVANCE(31);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '|') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '!') ADVANCE(2);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == ',') ADVANCE(31);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead == '.') ADVANCE(19);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '=') ADVANCE(3);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(20);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == '|') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_trim);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(11);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'o') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(35);
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(55);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 50:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_assign);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_render);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_unless);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_contains);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_endunless);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 6, .external_lex_state = 1},
  [2] = {.lex_state = 6, .external_lex_state = 1},
  [3] = {.lex_state = 6, .external_lex_state = 1},
  [4] = {.lex_state = 6, .external_lex_state = 1},
  [5] = {.lex_state = 6, .external_lex_state = 1},
  [6] = {.lex_state = 6, .external_lex_state = 1},
  [7] = {.lex_state = 6, .external_lex_state = 1},
  [8] = {.lex_state = 6, .external_lex_state = 1},
  [9] = {.lex_state = 6, .external_lex_state = 1},
  [10] = {.lex_state = 6, .external_lex_state = 1},
  [11] = {.lex_state = 6, .external_lex_state = 1},
  [12] = {.lex_state = 6, .external_lex_state = 1},
  [13] = {.lex_state = 6, .external_lex_state = 1},
  [14] = {.lex_state = 6, .external_lex_state = 1},
  [15] = {.lex_state = 6, .external_lex_state = 1},
  [16] = {.lex_state = 6, .external_lex_state = 1},
  [17] = {.lex_state = 6, .external_lex_state = 1},
  [18] = {.lex_state = 6, .external_lex_state = 1},
  [19] = {.lex_state = 6, .external_lex_state = 1},
  [20] = {.lex_state = 6, .external_lex_state = 1},
  [21] = {.lex_state = 6, .external_lex_state = 1},
  [22] = {.lex_state = 6, .external_lex_state = 1},
  [23] = {.lex_state = 6, .external_lex_state = 1},
  [24] = {.lex_state = 6, .external_lex_state = 1},
  [25] = {.lex_state = 6, .external_lex_state = 1},
  [26] = {.lex_state = 6, .external_lex_state = 1},
  [27] = {.lex_state = 6, .external_lex_state = 1},
  [28] = {.lex_state = 6, .external_lex_state = 1},
  [29] = {.lex_state = 6, .external_lex_state = 1},
  [30] = {.lex_state = 6, .external_lex_state = 1},
  [31] = {.lex_state = 6, .external_lex_state = 1},
  [32] = {.lex_state = 6, .external_lex_state = 1},
  [33] = {.lex_state = 6, .external_lex_state = 1},
  [34] = {.lex_state = 6, .external_lex_state = 1},
  [35] = {.lex_state = 6, .external_lex_state = 1},
  [36] = {.lex_state = 6, .external_lex_state = 1},
  [37] = {.lex_state = 6, .external_lex_state = 1},
  [38] = {.lex_state = 6, .external_lex_state = 1},
  [39] = {.lex_state = 6, .external_lex_state = 1},
  [40] = {.lex_state = 6, .external_lex_state = 1},
  [41] = {.lex_state = 6, .external_lex_state = 1},
  [42] = {.lex_state = 6, .external_lex_state = 1},
  [43] = {.lex_state = 6, .external_lex_state = 1},
  [44] = {.lex_state = 6, .external_lex_state = 1},
  [45] = {.lex_state = 6, .external_lex_state = 1},
  [46] = {.lex_state = 6, .external_lex_state = 1},
  [47] = {.lex_state = 6, .external_lex_state = 1},
  [48] = {.lex_state = 6, .external_lex_state = 1},
  [49] = {.lex_state = 6, .external_lex_state = 1},
  [50] = {.lex_state = 6, .external_lex_state = 1},
  [51] = {.lex_state = 6, .external_lex_state = 1},
  [52] = {.lex_state = 6, .external_lex_state = 1},
  [53] = {.lex_state = 6, .external_lex_state = 1},
  [54] = {.lex_state = 6, .external_lex_state = 1},
  [55] = {.lex_state = 6, .external_lex_state = 1},
  [56] = {.lex_state = 6, .external_lex_state = 1},
  [57] = {.lex_state = 0, .external_lex_state = 1},
  [58] = {.lex_state = 0, .external_lex_state = 1},
  [59] = {.lex_state = 0, .external_lex_state = 1},
  [60] = {.lex_state = 0, .external_lex_state = 1},
  [61] = {.lex_state = 0, .external_lex_state = 1},
  [62] = {.lex_state = 0, .external_lex_state = 1},
  [63] = {.lex_state = 0, .external_lex_state = 1},
  [64] = {.lex_state = 0, .external_lex_state = 1},
  [65] = {.lex_state = 0, .external_lex_state = 1},
  [66] = {.lex_state = 0, .external_lex_state = 1},
  [67] = {.lex_state = 10, .external_lex_state = 1},
  [68] = {.lex_state = 0, .external_lex_state = 1},
  [69] = {.lex_state = 0, .external_lex_state = 1},
  [70] = {.lex_state = 0, .external_lex_state = 1},
  [71] = {.lex_state = 0, .external_lex_state = 1},
  [72] = {.lex_state = 4, .external_lex_state = 1},
  [73] = {.lex_state = 0, .external_lex_state = 1},
  [74] = {.lex_state = 0, .external_lex_state = 1},
  [75] = {.lex_state = 0, .external_lex_state = 1},
  [76] = {.lex_state = 0, .external_lex_state = 1},
  [77] = {.lex_state = 13, .external_lex_state = 1},
};

enum {
  ts_external_token_comment = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_trim] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_assign] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_contains] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_render] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_endunless] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_program] = STATE(75),
    [sym__statement] = STATE(47),
    [sym__literal] = STATE(15),
    [sym_string] = STATE(15),
    [sym_number] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_assignment] = STATE(47),
    [sym__control_flow] = STATE(47),
    [sym__expression] = STATE(15),
    [sym_access] = STATE(15),
    [sym_filter] = STATE(15),
    [sym_include_expression] = STATE(15),
    [sym_render_expression] = STATE(15),
    [sym_binary_expression] = STATE(15),
    [sym_unless_tag] = STATE(47),
    [sym_if_tag] = STATE(47),
    [aux_sym_program_repeat1] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_assign] = ACTIONS(17),
    [anon_sym_include] = ACTIONS(19),
    [anon_sym_render] = ACTIONS(21),
    [anon_sym_unless] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [2] = {
    [sym__statement] = STATE(47),
    [sym__literal] = STATE(15),
    [sym_string] = STATE(15),
    [sym_number] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_assignment] = STATE(47),
    [sym__control_flow] = STATE(47),
    [sym__expression] = STATE(15),
    [sym_access] = STATE(15),
    [sym_comparision_operator] = STATE(38),
    [sym_logical_operator] = STATE(39),
    [sym_filter] = STATE(15),
    [sym_include_expression] = STATE(15),
    [sym_render_expression] = STATE(15),
    [sym_binary_expression] = STATE(15),
    [sym_unless_tag] = STATE(47),
    [sym_if_tag] = STATE(47),
    [sym_elseif_tag] = STATE(60),
    [sym_else_tag] = STATE(65),
    [aux_sym_program_repeat1] = STATE(5),
    [aux_sym_if_tag_repeat1] = STATE(58),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_assign] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_BANG_EQ] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(29),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_contains] = ACTIONS(29),
    [anon_sym_or] = ACTIONS(31),
    [anon_sym_and] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(33),
    [anon_sym_include] = ACTIONS(19),
    [anon_sym_render] = ACTIONS(21),
    [anon_sym_unless] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_endif] = ACTIONS(35),
    [anon_sym_elseif] = ACTIONS(37),
    [anon_sym_else] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
  },
  [3] = {
    [sym__statement] = STATE(47),
    [sym__literal] = STATE(15),
    [sym_string] = STATE(15),
    [sym_number] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_assignment] = STATE(47),
    [sym__control_flow] = STATE(47),
    [sym__expression] = STATE(15),
    [sym_access] = STATE(15),
    [sym_comparision_operator] = STATE(38),
    [sym_logical_operator] = STATE(39),
    [sym_filter] = STATE(15),
    [sym_include_expression] = STATE(15),
    [sym_render_expression] = STATE(15),
    [sym_binary_expression] = STATE(15),
    [sym_unless_tag] = STATE(47),
    [sym_if_tag] = STATE(47),
    [aux_sym_program_repeat1] = STATE(7),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_assign] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_BANG_EQ] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(29),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_contains] = ACTIONS(29),
    [anon_sym_or] = ACTIONS(31),
    [anon_sym_and] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(33),
    [anon_sym_include] = ACTIONS(19),
    [anon_sym_render] = ACTIONS(21),
    [anon_sym_unless] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_endif] = ACTIONS(41),
    [anon_sym_elseif] = ACTIONS(41),
    [anon_sym_else] = ACTIONS(41),
    [sym_comment] = ACTIONS(3),
  },
  [4] = {
    [sym__statement] = STATE(47),
    [sym__literal] = STATE(15),
    [sym_string] = STATE(15),
    [sym_number] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_assignment] = STATE(47),
    [sym__control_flow] = STATE(47),
    [sym__expression] = STATE(15),
    [sym_access] = STATE(15),
    [sym_comparision_operator] = STATE(38),
    [sym_logical_operator] = STATE(39),
    [sym_filter] = STATE(15),
    [sym_include_expression] = STATE(15),
    [sym_render_expression] = STATE(15),
    [sym_binary_expression] = STATE(15),
    [sym_unless_tag] = STATE(47),
    [sym_if_tag] = STATE(47),
    [aux_sym_program_repeat1] = STATE(24),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_assign] = ACTIONS(17),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_BANG_EQ] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(29),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_contains] = ACTIONS(29),
    [anon_sym_or] = ACTIONS(31),
    [anon_sym_and] = ACTIONS(31),
    [anon_sym_PIPE] = ACTIONS(33),
    [anon_sym_include] = ACTIONS(19),
    [anon_sym_render] = ACTIONS(21),
    [anon_sym_unless] = ACTIONS(23),
    [anon_sym_endunless] = ACTIONS(43),
    [anon_sym_if] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [5] = {
    [sym__statement] = STATE(47),
    [sym__literal] = STATE(15),
    [sym_string] = STATE(15),
    [sym_number] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_assignment] = STATE(47),
    [sym__control_flow] = STATE(47),
    [sym__expression] = STATE(15),
    [sym_access] = STATE(15),
    [sym_filter] = STATE(15),
    [sym_include_expression] = STATE(15),
    [sym_render_expression] = STATE(15),
    [sym_binary_expression] = STATE(15),
    [sym_unless_tag] = STATE(47),
    [sym_if_tag] = STATE(47),
    [sym_elseif_tag] = STATE(60),
    [sym_else_tag] = STATE(66),
    [aux_sym_program_repeat1] = STATE(6),
    [aux_sym_if_tag_repeat1] = STATE(57),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(9),
    [anon_sym_DQUOTE] = ACTIONS(11),
    [aux_sym_number_token1] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_assign] = ACTIONS(17),
    [anon_sym_include] = ACTIONS(19),
    [anon_sym_render] = ACTIONS(21),
    [anon_sym_unless] = ACTIONS(23),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_endif] = ACTIONS(45),
    [anon_sym_elseif] = ACTIONS(37),
    [anon_sym_else] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
  },
  [6] = {
    [sym__statement] = STATE(47),
    [sym__literal] = STATE(15),
    [sym_string] = STATE(15),
    [sym_number] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_assignment] = STATE(47),
    [sym__control_flow] = STATE(47),
    [sym__expression] = STATE(15),
    [sym_access] = STATE(15),
    [sym_filter] = STATE(15),
    [sym_include_expression] = STATE(15),
    [sym_render_expression] = STATE(15),
    [sym_binary_expression] = STATE(15),
    [sym_unless_tag] = STATE(47),
    [sym_if_tag] = STATE(47),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_identifier] = ACTIONS(49),
    [anon_sym_SQUOTE] = ACTIONS(52),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [aux_sym_number_token1] = ACTIONS(58),
    [anon_sym_true] = ACTIONS(61),
    [anon_sym_false] = ACTIONS(61),
    [anon_sym_assign] = ACTIONS(64),
    [anon_sym_include] = ACTIONS(67),
    [anon_sym_render] = ACTIONS(70),
    [anon_sym_unless] = ACTIONS(73),
    [anon_sym_endunless] = ACTIONS(76),
    [anon_sym_if] = ACTIONS(78),
    [anon_sym_endif] = ACTIONS(76),
    [anon_sym_elseif] = ACTIONS(76),
    [anon_sym_else] = ACTIONS(76),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(17), 1,
      anon_sym_assign,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(23), 1,
      anon_sym_unless,
    ACTIONS(25), 1,
      anon_sym_if,
    STATE(6), 1,
      aux_sym_program_repeat1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 3,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
    STATE(47), 5,
      sym__statement,
      sym_assignment,
      sym__control_flow,
      sym_unless_tag,
      sym_if_tag,
    STATE(15), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [62] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_COLON,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(85), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [105] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_DOT,
    ACTIONS(98), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      aux_sym_access_repeat1,
    ACTIONS(91), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(93), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [148] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    STATE(11), 1,
      aux_sym_access_repeat1,
    ACTIONS(101), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(103), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [191] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      aux_sym_access_repeat1,
    ACTIONS(109), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(111), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [234] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(17), 1,
      anon_sym_assign,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(23), 1,
      anon_sym_unless,
    ACTIONS(25), 1,
      anon_sym_if,
    ACTIONS(113), 1,
      anon_sym_endif,
    STATE(14), 1,
      aux_sym_program_repeat1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 5,
      sym__statement,
      sym_assignment,
      sym__control_flow,
      sym_unless_tag,
      sym_if_tag,
    STATE(15), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [294] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 11,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
    ACTIONS(117), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [330] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(17), 1,
      anon_sym_assign,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(23), 1,
      anon_sym_unless,
    ACTIONS(25), 1,
      anon_sym_if,
    ACTIONS(119), 1,
      anon_sym_endif,
    STATE(6), 1,
      aux_sym_program_repeat1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 5,
      sym__statement,
      sym_assignment,
      sym__control_flow,
      sym_unless_tag,
      sym_if_tag,
    STATE(15), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [390] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PIPE,
    STATE(38), 1,
      sym_comparision_operator,
    STATE(39), 1,
      sym_logical_operator,
    ACTIONS(31), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
    ACTIONS(27), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(123), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [438] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(17), 1,
      anon_sym_assign,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(23), 1,
      anon_sym_unless,
    ACTIONS(25), 1,
      anon_sym_if,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_program_repeat1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 5,
      sym__statement,
      sym_assignment,
      sym__control_flow,
      sym_unless_tag,
      sym_if_tag,
    STATE(15), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [498] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 10,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_LBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(129), 18,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      anon_sym_DOT,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [534] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PIPE,
    STATE(38), 1,
      sym_comparision_operator,
    STATE(39), 1,
      sym_logical_operator,
    ACTIONS(31), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
    ACTIONS(27), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(131), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(133), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [582] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_PIPE,
    STATE(38), 1,
      sym_comparision_operator,
    STATE(39), 1,
      sym_logical_operator,
    ACTIONS(31), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
    ACTIONS(27), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(137), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [630] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    STATE(21), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(85), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [670] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(141), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [710] = 7,
    ACTIONS(3), 1,
      sym_comment,
    STATE(38), 1,
      sym_comparision_operator,
    STATE(39), 1,
      sym_logical_operator,
    ACTIONS(29), 3,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
    ACTIONS(27), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_PIPE,
    ACTIONS(137), 14,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [754] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_COLON,
    ACTIONS(143), 10,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
    ACTIONS(145), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [792] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(17), 1,
      anon_sym_assign,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(23), 1,
      anon_sym_unless,
    ACTIONS(25), 1,
      anon_sym_if,
    ACTIONS(147), 1,
      anon_sym_endunless,
    STATE(6), 1,
      aux_sym_program_repeat1,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 5,
      sym__statement,
      sym_assignment,
      sym__control_flow,
      sym_unless_tag,
      sym_if_tag,
    STATE(15), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [852] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 10,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_LBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(151), 18,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      anon_sym_DOT,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [888] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(145), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [928] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 10,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
    ACTIONS(145), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [963] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 10,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
    ACTIONS(158), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [998] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 10,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
    ACTIONS(162), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_COLON,
    ACTIONS(164), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(166), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1070] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 10,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
      anon_sym_COMMA,
    ACTIONS(172), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(176), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1139] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(180), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1173] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 9,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_PIPE,
    ACTIONS(184), 17,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1207] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(18), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [1245] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(2), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [1283] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [1321] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [1359] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [1397] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(19), 1,
      anon_sym_include,
    ACTIONS(21), 1,
      anon_sym_render,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [1435] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(188), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1459] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(192), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(196), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1507] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(200), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(204), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1555] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(208), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(212), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1603] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(216), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1627] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(220), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1651] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(224), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1675] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 4,
      ts_builtin_sym_end,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(228), 12,
      anon_sym_true,
      anon_sym_false,
      anon_sym_assign,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
      anon_sym_unless,
      anon_sym_endunless,
      anon_sym_if,
      anon_sym_endif,
      anon_sym_elseif,
      anon_sym_else,
  [1699] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(230), 1,
      sym_identifier,
    STATE(34), 1,
      sym_argument_list,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 5,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym_argument,
  [1729] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(232), 1,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 5,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym_argument,
  [1756] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      aux_sym_number_token1,
    ACTIONS(234), 1,
      sym_identifier,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(31), 4,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
  [1782] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 3,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(236), 5,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
  [1798] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 3,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(240), 5,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
  [1814] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_else,
    ACTIONS(244), 1,
      anon_sym_endif,
    ACTIONS(246), 1,
      anon_sym_elseif,
    STATE(59), 1,
      aux_sym_if_tag_repeat1,
    STATE(60), 1,
      sym_elseif_tag,
    STATE(68), 1,
      sym_else_tag,
  [1836] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 1,
      anon_sym_else,
    ACTIONS(246), 1,
      anon_sym_elseif,
    ACTIONS(248), 1,
      anon_sym_endif,
    STATE(59), 1,
      aux_sym_if_tag_repeat1,
    STATE(60), 1,
      sym_elseif_tag,
    STATE(64), 1,
      sym_else_tag,
  [1858] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_endif,
    ACTIONS(252), 1,
      anon_sym_elseif,
    ACTIONS(255), 1,
      anon_sym_else,
    STATE(59), 1,
      aux_sym_if_tag_repeat1,
    STATE(60), 1,
      sym_elseif_tag,
  [1877] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_else,
    ACTIONS(257), 2,
      anon_sym_endif,
      anon_sym_elseif,
  [1888] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      sym_string,
  [1901] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_string,
  [1914] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      sym_string,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_endif,
  [1934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_endif,
  [1941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_endif,
  [1948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      aux_sym_string_token1,
  [1955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_endif,
  [1962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_RBRACK,
  [1969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym_identifier,
  [1976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_identifier,
  [1983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_EQ,
  [1990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_DQUOTE,
  [1997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_SQUOTE,
  [2004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [2011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_identifier,
  [2018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      aux_sym_string_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 62,
  [SMALL_STATE(9)] = 105,
  [SMALL_STATE(10)] = 148,
  [SMALL_STATE(11)] = 191,
  [SMALL_STATE(12)] = 234,
  [SMALL_STATE(13)] = 294,
  [SMALL_STATE(14)] = 330,
  [SMALL_STATE(15)] = 390,
  [SMALL_STATE(16)] = 438,
  [SMALL_STATE(17)] = 498,
  [SMALL_STATE(18)] = 534,
  [SMALL_STATE(19)] = 582,
  [SMALL_STATE(20)] = 630,
  [SMALL_STATE(21)] = 670,
  [SMALL_STATE(22)] = 710,
  [SMALL_STATE(23)] = 754,
  [SMALL_STATE(24)] = 792,
  [SMALL_STATE(25)] = 852,
  [SMALL_STATE(26)] = 888,
  [SMALL_STATE(27)] = 928,
  [SMALL_STATE(28)] = 963,
  [SMALL_STATE(29)] = 998,
  [SMALL_STATE(30)] = 1033,
  [SMALL_STATE(31)] = 1070,
  [SMALL_STATE(32)] = 1105,
  [SMALL_STATE(33)] = 1139,
  [SMALL_STATE(34)] = 1173,
  [SMALL_STATE(35)] = 1207,
  [SMALL_STATE(36)] = 1245,
  [SMALL_STATE(37)] = 1283,
  [SMALL_STATE(38)] = 1321,
  [SMALL_STATE(39)] = 1359,
  [SMALL_STATE(40)] = 1397,
  [SMALL_STATE(41)] = 1435,
  [SMALL_STATE(42)] = 1459,
  [SMALL_STATE(43)] = 1483,
  [SMALL_STATE(44)] = 1507,
  [SMALL_STATE(45)] = 1531,
  [SMALL_STATE(46)] = 1555,
  [SMALL_STATE(47)] = 1579,
  [SMALL_STATE(48)] = 1603,
  [SMALL_STATE(49)] = 1627,
  [SMALL_STATE(50)] = 1651,
  [SMALL_STATE(51)] = 1675,
  [SMALL_STATE(52)] = 1699,
  [SMALL_STATE(53)] = 1729,
  [SMALL_STATE(54)] = 1756,
  [SMALL_STATE(55)] = 1782,
  [SMALL_STATE(56)] = 1798,
  [SMALL_STATE(57)] = 1814,
  [SMALL_STATE(58)] = 1836,
  [SMALL_STATE(59)] = 1858,
  [SMALL_STATE(60)] = 1877,
  [SMALL_STATE(61)] = 1888,
  [SMALL_STATE(62)] = 1901,
  [SMALL_STATE(63)] = 1914,
  [SMALL_STATE(64)] = 1927,
  [SMALL_STATE(65)] = 1934,
  [SMALL_STATE(66)] = 1941,
  [SMALL_STATE(67)] = 1948,
  [SMALL_STATE(68)] = 1955,
  [SMALL_STATE(69)] = 1962,
  [SMALL_STATE(70)] = 1969,
  [SMALL_STATE(71)] = 1976,
  [SMALL_STATE(72)] = 1983,
  [SMALL_STATE(73)] = 1990,
  [SMALL_STATE(74)] = 1997,
  [SMALL_STATE(75)] = 2004,
  [SMALL_STATE(76)] = 2011,
  [SMALL_STATE(77)] = 2018,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_tag, 2, .production_id = 6),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(10),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(67),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(77),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(28),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(29),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(76),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(63),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(62),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(37),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(36),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_tag, 3, .production_id = 11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5), SHIFT_REPEAT(71),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5), SHIFT_REPEAT(61),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_access, 2, .production_id = 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_access, 2, .production_id = 1),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_tag, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_tag, 2, .production_id = 12),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 3, .production_id = 4),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_access_repeat1, 3, .production_id = 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, .production_id = 10),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, .production_id = 10),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 9),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 9),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 4),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 4),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(53),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 3, .production_id = 8),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter, 3, .production_id = 8),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, .production_id = 20),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 3, .production_id = 20),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_expression, 2, .production_id = 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_expression, 2, .production_id = 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_render_expression, 2, .production_id = 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_render_expression, 2, .production_id = 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 5, .production_id = 8),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter, 5, .production_id = 8),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 3, .production_id = 6),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 3, .production_id = 6),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 5, .production_id = 16),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 5, .production_id = 16),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 5, .production_id = 18),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 5, .production_id = 18),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 5, .production_id = 17),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 5, .production_id = 17),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 6, .production_id = 19),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 6, .production_id = 19),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_tag, 4, .production_id = 11),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_tag, 4, .production_id = 11),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 4, .production_id = 13),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 4, .production_id = 13),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 4, .production_id = 11),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 4, .production_id = 11),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_tag, 4, .production_id = 14),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_tag, 4, .production_id = 14),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_tag, 3, .production_id = 6),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_tag, 3, .production_id = 6),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_operator, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_operator, 1),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparision_operator, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparision_operator, 1),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_tag_repeat1, 2, .production_id = 15),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_tag_repeat1, 2, .production_id = 15), SHIFT_REPEAT(40),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_tag_repeat1, 2, .production_id = 15),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_tag_repeat1, 1, .production_id = 7),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_tag_repeat1, 1, .production_id = 7),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [281] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_liquid_external_scanner_create(void);
void tree_sitter_liquid_external_scanner_destroy(void *);
bool tree_sitter_liquid_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_liquid_external_scanner_serialize(void *, char *);
void tree_sitter_liquid_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_liquid(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_liquid_external_scanner_create,
      tree_sitter_liquid_external_scanner_destroy,
      tree_sitter_liquid_external_scanner_scan,
      tree_sitter_liquid_external_scanner_serialize,
      tree_sitter_liquid_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
