#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 129
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 1
#define TOKEN_COUNT 44
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 16
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 21

enum {
  sym_identifier = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_LBRACE_LBRACE_DASH = 3,
  anon_sym_RBRACE_RBRACE = 4,
  anon_sym_DASH_RBRACE_RBRACE = 5,
  anon_sym_LBRACE_PERCENT = 6,
  anon_sym_LBRACE_PERCENT_DASH = 7,
  anon_sym_PERCENT_RBRACE = 8,
  anon_sym_DASH_PERCENT_RBRACE = 9,
  sym_comment = 10,
  sym_trim = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_string_token1 = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_string_token2 = 15,
  aux_sym_number_token1 = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  anon_sym_assign = 19,
  anon_sym_EQ = 20,
  anon_sym_DOT = 21,
  anon_sym_LBRACK = 22,
  anon_sym_RBRACK = 23,
  anon_sym_EQ_EQ = 24,
  anon_sym_BANG_EQ = 25,
  anon_sym_GT = 26,
  anon_sym_LT = 27,
  anon_sym_GT_EQ = 28,
  anon_sym_LT_EQ = 29,
  anon_sym_contains = 30,
  anon_sym_or = 31,
  anon_sym_and = 32,
  anon_sym_PIPE = 33,
  anon_sym_COLON = 34,
  anon_sym_COMMA = 35,
  anon_sym_include = 36,
  anon_sym_render = 37,
  anon_sym_unless = 38,
  anon_sym_endunless = 39,
  anon_sym_if = 40,
  anon_sym_endif = 41,
  anon_sym_elseif = 42,
  anon_sym_else = 43,
  sym_program = 44,
  sym__statement = 45,
  sym__literal = 46,
  sym_string = 47,
  sym_number = 48,
  sym_boolean = 49,
  sym_assignment = 50,
  sym__control_flow = 51,
  sym__expression = 52,
  sym_access = 53,
  sym_comparision_operator = 54,
  sym_logical_operator = 55,
  sym_filter = 56,
  sym_argument_list = 57,
  sym_argument = 58,
  sym_include_expression = 59,
  sym_render_expression = 60,
  sym_binary_expression = 61,
  sym_unless_expression = 62,
  sym_if_expression = 63,
  sym_elseif_expression = 64,
  sym_else_expression = 65,
  aux_sym_program_repeat1 = 66,
  aux_sym_access_repeat1 = 67,
  aux_sym_argument_list_repeat1 = 68,
  aux_sym_if_expression_repeat1 = 69,
  alias_sym_block = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_LBRACE_LBRACE_DASH] = "{{-",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DASH_RBRACE_RBRACE] = "-}}",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_LBRACE_PERCENT_DASH] = "{%-",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_DASH_PERCENT_RBRACE] = "-%}",
  [sym_comment] = "comment",
  [sym_trim] = "trim",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [aux_sym_number_token1] = "number_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_assign] = "assign",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_contains] = "contains",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_PIPE] = "|",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_include] = "include",
  [anon_sym_render] = "render",
  [anon_sym_unless] = "unless",
  [anon_sym_endunless] = "endunless",
  [anon_sym_if] = "if",
  [anon_sym_endif] = "endif",
  [anon_sym_elseif] = "elseif",
  [anon_sym_else] = "else",
  [sym_program] = "program",
  [sym__statement] = "_statement",
  [sym__literal] = "_literal",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [sym_assignment] = "assignment",
  [sym__control_flow] = "_control_flow",
  [sym__expression] = "_expression",
  [sym_access] = "access",
  [sym_comparision_operator] = "comparision_operator",
  [sym_logical_operator] = "logical_operator",
  [sym_filter] = "filter",
  [sym_argument_list] = "argument_list",
  [sym_argument] = "argument",
  [sym_include_expression] = "include_expression",
  [sym_render_expression] = "render_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unless_expression] = "unless_expression",
  [sym_if_expression] = "if_expression",
  [sym_elseif_expression] = "elseif_expression",
  [sym_else_expression] = "else_expression",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_access_repeat1] = "access_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
  [aux_sym_if_expression_repeat1] = "if_expression_repeat1",
  [alias_sym_block] = "block",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_LBRACE_LBRACE_DASH] = anon_sym_LBRACE_LBRACE_DASH,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DASH_RBRACE_RBRACE] = anon_sym_DASH_RBRACE_RBRACE,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_LBRACE_PERCENT_DASH] = anon_sym_LBRACE_PERCENT_DASH,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_DASH_PERCENT_RBRACE] = anon_sym_DASH_PERCENT_RBRACE,
  [sym_comment] = sym_comment,
  [sym_trim] = sym_trim,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_assign] = anon_sym_assign,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_contains] = anon_sym_contains,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_render] = anon_sym_render,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_endunless] = anon_sym_endunless,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [sym_program] = sym_program,
  [sym__statement] = sym__statement,
  [sym__literal] = sym__literal,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [sym_assignment] = sym_assignment,
  [sym__control_flow] = sym__control_flow,
  [sym__expression] = sym__expression,
  [sym_access] = sym_access,
  [sym_comparision_operator] = sym_comparision_operator,
  [sym_logical_operator] = sym_logical_operator,
  [sym_filter] = sym_filter,
  [sym_argument_list] = sym_argument_list,
  [sym_argument] = sym_argument,
  [sym_include_expression] = sym_include_expression,
  [sym_render_expression] = sym_render_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unless_expression] = sym_unless_expression,
  [sym_if_expression] = sym_if_expression,
  [sym_elseif_expression] = sym_elseif_expression,
  [sym_else_expression] = sym_else_expression,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_access_repeat1] = aux_sym_access_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
  [aux_sym_if_expression_repeat1] = aux_sym_if_expression_repeat1,
  [alias_sym_block] = alias_sym_block,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_trim] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assign] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contains] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_render] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endunless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__control_flow] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_access] = {
    .visible = true,
    .named = true,
  },
  [sym_comparision_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_include_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_render_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_elseif_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_else_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_access_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_block] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_alternatives = 1,
  field_body = 2,
  field_condition = 3,
  field_consequence = 4,
  field_field = 5,
  field_include = 6,
  field_included_file = 7,
  field_key = 8,
  field_left = 9,
  field_name = 10,
  field_operand = 11,
  field_operator = 12,
  field_render = 13,
  field_rendered_file = 14,
  field_right = 15,
  field_value = 16,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternatives] = "alternatives",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_field] = "field",
  [field_include] = "include",
  [field_included_file] = "included_file",
  [field_key] = "key",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_render] = "render",
  [field_rendered_file] = "rendered_file",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 2},
  [9] = {.index = 16, .length = 1},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 1},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 2},
  [14] = {.index = 24, .length = 1},
  [15] = {.index = 25, .length = 2},
  [16] = {.index = 27, .length = 2},
  [17] = {.index = 29, .length = 3},
  [18] = {.index = 32, .length = 3},
  [19] = {.index = 35, .length = 3},
  [20] = {.index = 38, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_field, 1, .inherited = true},
    {field_operand, 0},
  [2] =
    {field_include, 0},
    {field_included_file, 1},
  [4] =
    {field_render, 0},
    {field_rendered_file, 1},
  [6] =
    {field_field, 1},
  [7] =
    {field_field, 0, .inherited = true},
    {field_field, 1, .inherited = true},
  [9] =
    {field_body, 0},
    {field_name, 2},
  [11] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [14] =
    {field_left, 1},
    {field_right, 3},
  [16] =
    {field_alternatives, 0},
  [17] =
    {field_alternatives, 0, .inherited = true},
    {field_alternatives, 1, .inherited = true},
  [19] =
    {field_condition, 2},
  [20] =
    {field_key, 0},
    {field_value, 2},
  [22] =
    {field_condition, 2},
    {field_consequence, 4},
  [24] =
    {field_consequence, 3},
  [25] =
    {field_alternatives, 4},
    {field_condition, 2},
  [27] =
    {field_alternatives, 4, .inherited = true},
    {field_condition, 2},
  [29] =
    {field_alternatives, 5},
    {field_condition, 2},
    {field_consequence, 4},
  [32] =
    {field_alternatives, 5, .inherited = true},
    {field_condition, 2},
    {field_consequence, 4},
  [35] =
    {field_alternatives, 4, .inherited = true},
    {field_alternatives, 5},
    {field_condition, 2},
  [38] =
    {field_alternatives, 5, .inherited = true},
    {field_alternatives, 6},
    {field_condition, 2},
    {field_consequence, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [13] = {
    [4] = alias_sym_block,
  },
  [14] = {
    [3] = alias_sym_block,
  },
  [17] = {
    [4] = alias_sym_block,
  },
  [18] = {
    [4] = alias_sym_block,
  },
  [20] = {
    [4] = alias_sym_block,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym_program_repeat1, 2,
    aux_sym_program_repeat1,
    alias_sym_block,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == ',') ADVANCE(55);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(50);
      if (lookahead == '=') ADVANCE(41);
      if (lookahead == '>') ADVANCE(49);
      if (lookahead == '[') ADVANCE(44);
      if (lookahead == ']') ADVANCE(45);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '|') ADVANCE(53);
      if (lookahead == '}') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == ',') ADVANCE(55);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == ':') ADVANCE(54);
      if (lookahead == '<') ADVANCE(50);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '>') ADVANCE(49);
      if (lookahead == ']') ADVANCE(45);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '|') ADVANCE(53);
      if (lookahead == '}') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '%') ADVANCE(13);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '<') ADVANCE(50);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '>') ADVANCE(49);
      if (lookahead == '[') ADVANCE(44);
      if (lookahead == '|') ADVANCE(53);
      if (lookahead == '}') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(24);
      if (lookahead == '{') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '%') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '}') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(12)
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 16:
      if (lookahead == '}') ADVANCE(23);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(6);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '-') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_RBRACE_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      if (lookahead == '-') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT_DASH);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH_PERCENT_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(6);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_trim);
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '}') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == 'o') ADVANCE(6);
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(10);
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(35);
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(42);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(46);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(50);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(53);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 48:
      if (lookahead == 'd') ADVANCE(55);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 50:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_assign);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_render);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_unless);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(61);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_contains);
      END_STATE();
    case 62:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_endunless);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 12},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 33},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 36},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_PERCENT_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_trim] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_assign] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_contains] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_render] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_endunless] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(127),
    [sym__statement] = STATE(78),
    [sym__control_flow] = STATE(78),
    [sym_unless_expression] = STATE(78),
    [sym_if_expression] = STATE(78),
    [aux_sym_program_repeat1] = STATE(46),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE_DASH] = ACTIONS(7),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(9),
    [anon_sym_LBRACE_PERCENT_DASH] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(23), 1,
      anon_sym_assign,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(29), 1,
      anon_sym_unless,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(33), 1,
      anon_sym_endif,
    ACTIONS(35), 1,
      anon_sym_elseif,
    ACTIONS(37), 1,
      anon_sym_else,
    STATE(110), 1,
      sym_assignment,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [56] = 15,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(23), 1,
      anon_sym_assign,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(29), 1,
      anon_sym_unless,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(35), 1,
      anon_sym_elseif,
    ACTIONS(37), 1,
      anon_sym_else,
    ACTIONS(39), 1,
      anon_sym_endif,
    STATE(110), 1,
      sym_assignment,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [112] = 13,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(23), 1,
      anon_sym_assign,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(29), 1,
      anon_sym_unless,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(41), 1,
      anon_sym_endunless,
    STATE(110), 1,
      sym_assignment,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [162] = 13,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(23), 1,
      anon_sym_assign,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(29), 1,
      anon_sym_unless,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(43), 1,
      anon_sym_endunless,
    STATE(110), 1,
      sym_assignment,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [212] = 12,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(23), 1,
      anon_sym_assign,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(29), 1,
      anon_sym_unless,
    ACTIONS(31), 1,
      anon_sym_if,
    STATE(110), 1,
      sym_assignment,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [259] = 10,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(23), 1,
      anon_sym_assign,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    STATE(93), 1,
      sym_assignment,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [300] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [335] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [370] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [405] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(23), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [440] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(37), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [475] = 8,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      anon_sym_include,
    ACTIONS(27), 1,
      anon_sym_render,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 10,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym__expression,
      sym_access,
      sym_filter,
      sym_include_expression,
      sym_render_expression,
      sym_binary_expression,
  [510] = 5,
    ACTIONS(47), 1,
      anon_sym_DOT,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    STATE(14), 1,
      aux_sym_access_repeat1,
    ACTIONS(53), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(45), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [538] = 5,
    ACTIONS(59), 1,
      anon_sym_COLON,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(57), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(55), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [566] = 5,
    ACTIONS(65), 1,
      anon_sym_DOT,
    ACTIONS(67), 1,
      anon_sym_LBRACK,
    STATE(17), 1,
      aux_sym_access_repeat1,
    ACTIONS(69), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(63), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [594] = 5,
    ACTIONS(65), 1,
      anon_sym_DOT,
    ACTIONS(67), 1,
      anon_sym_LBRACK,
    STATE(14), 1,
      aux_sym_access_repeat1,
    ACTIONS(73), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [622] = 3,
    ACTIONS(59), 1,
      anon_sym_COLON,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 13,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [645] = 4,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(25), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(57), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(55), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [670] = 2,
    ACTIONS(81), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(79), 14,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [691] = 7,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(83), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
  [722] = 7,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(93), 4,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
  [753] = 5,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
    ACTIONS(93), 7,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [780] = 4,
    ACTIONS(95), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [805] = 4,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(100), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(98), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [830] = 2,
    ACTIONS(104), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(102), 14,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [851] = 2,
    ACTIONS(108), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(106), 14,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [872] = 3,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(112), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(110), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [894] = 2,
    ACTIONS(77), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 13,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [914] = 2,
    ACTIONS(118), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(116), 13,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [934] = 2,
    ACTIONS(122), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(120), 13,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [954] = 2,
    ACTIONS(126), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(124), 13,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
      anon_sym_COMMA,
  [974] = 7,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(128), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
  [1003] = 2,
    ACTIONS(132), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(130), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [1022] = 7,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(128), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
  [1051] = 2,
    ACTIONS(136), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(134), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [1070] = 7,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(138), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
  [1099] = 7,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(140), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
  [1128] = 7,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      sym_logical_operator,
    STATE(11), 1,
      sym_comparision_operator,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(89), 2,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(142), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
    ACTIONS(85), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
  [1157] = 2,
    ACTIONS(146), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(144), 12,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_contains,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PIPE,
  [1176] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(42), 1,
      aux_sym_program_repeat1,
    STATE(81), 1,
      aux_sym_if_expression_repeat1,
    STATE(92), 1,
      sym_else_expression,
    STATE(94), 1,
      sym_elseif_expression,
    ACTIONS(148), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1208] = 9,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_program_repeat1,
    STATE(80), 1,
      aux_sym_if_expression_repeat1,
    STATE(94), 1,
      sym_elseif_expression,
    STATE(99), 1,
      sym_else_expression,
    ACTIONS(150), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1240] = 7,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(152), 1,
      sym_identifier,
    STATE(36), 1,
      sym_argument_list,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(19), 5,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym_argument,
  [1267] = 7,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(159), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(165), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_program_repeat1,
    ACTIONS(162), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1293] = 6,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(29), 5,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
      sym_argument,
  [1317] = 7,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    ACTIONS(170), 1,
      ts_builtin_sym_end,
    STATE(44), 1,
      aux_sym_program_repeat1,
    ACTIONS(9), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1343] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(50), 1,
      aux_sym_program_repeat1,
    ACTIONS(172), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1366] = 6,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      aux_sym_number_token1,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 4,
      sym__literal,
      sym_string,
      sym_number,
      sym_boolean,
  [1389] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(52), 1,
      aux_sym_program_repeat1,
    ACTIONS(176), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1412] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_program_repeat1,
    ACTIONS(178), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1435] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(53), 1,
      aux_sym_program_repeat1,
    ACTIONS(180), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1458] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_program_repeat1,
    ACTIONS(182), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1481] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE_DASH,
    ACTIONS(11), 1,
      sym_comment,
    STATE(44), 1,
      aux_sym_program_repeat1,
    ACTIONS(184), 2,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(78), 4,
      sym__statement,
      sym__control_flow,
      sym_unless_expression,
      sym_if_expression,
  [1504] = 2,
    ACTIONS(188), 3,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(186), 5,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
  [1517] = 2,
    ACTIONS(192), 3,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      aux_sym_number_token1,
    ACTIONS(190), 5,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_include,
      anon_sym_render,
  [1530] = 2,
    ACTIONS(194), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(196), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1541] = 2,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1552] = 2,
    ACTIONS(202), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(204), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1563] = 2,
    ACTIONS(206), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1574] = 2,
    ACTIONS(206), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1585] = 2,
    ACTIONS(210), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(212), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1596] = 2,
    ACTIONS(206), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1607] = 2,
    ACTIONS(210), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(212), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1618] = 2,
    ACTIONS(214), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(216), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1629] = 2,
    ACTIONS(210), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(212), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1640] = 2,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1651] = 2,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(224), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1662] = 2,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1673] = 2,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(228), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1684] = 2,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1695] = 2,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1706] = 2,
    ACTIONS(206), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(208), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1717] = 2,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1728] = 2,
    ACTIONS(210), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(212), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1739] = 2,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(220), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1750] = 2,
    ACTIONS(230), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(232), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1761] = 2,
    ACTIONS(234), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(236), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1772] = 2,
    ACTIONS(238), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(240), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1783] = 2,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE_DASH,
      sym_comment,
    ACTIONS(200), 3,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_PERCENT_DASH,
  [1794] = 5,
    ACTIONS(242), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(244), 1,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(82), 1,
      aux_sym_if_expression_repeat1,
    STATE(94), 1,
      sym_elseif_expression,
    STATE(101), 1,
      sym_else_expression,
  [1810] = 5,
    ACTIONS(246), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(248), 1,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(82), 1,
      aux_sym_if_expression_repeat1,
    STATE(90), 1,
      sym_else_expression,
    STATE(94), 1,
      sym_elseif_expression,
  [1826] = 4,
    ACTIONS(250), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(253), 1,
      anon_sym_LBRACE_PERCENT_DASH,
    STATE(82), 1,
      aux_sym_if_expression_repeat1,
    STATE(94), 1,
      sym_elseif_expression,
  [1839] = 3,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      sym_string,
  [1849] = 3,
    ACTIONS(37), 1,
      anon_sym_else,
    ACTIONS(256), 1,
      anon_sym_endif,
    ACTIONS(258), 1,
      anon_sym_elseif,
  [1859] = 3,
    ACTIONS(37), 1,
      anon_sym_else,
    ACTIONS(258), 1,
      anon_sym_elseif,
    ACTIONS(260), 1,
      anon_sym_endif,
  [1869] = 3,
    ACTIONS(37), 1,
      anon_sym_else,
    ACTIONS(258), 1,
      anon_sym_elseif,
    ACTIONS(262), 1,
      anon_sym_endif,
  [1879] = 3,
    ACTIONS(37), 1,
      anon_sym_else,
    ACTIONS(258), 1,
      anon_sym_elseif,
    ACTIONS(264), 1,
      anon_sym_endif,
  [1889] = 3,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(118), 1,
      sym_string,
  [1899] = 3,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_string,
  [1909] = 2,
    ACTIONS(266), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(268), 1,
      anon_sym_LBRACE_PERCENT_DASH,
  [1916] = 1,
    ACTIONS(270), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [1921] = 2,
    ACTIONS(272), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(274), 1,
      anon_sym_LBRACE_PERCENT_DASH,
  [1928] = 1,
    ACTIONS(128), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DASH_RBRACE_RBRACE,
  [1933] = 2,
    ACTIONS(276), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(278), 1,
      anon_sym_LBRACE_PERCENT_DASH,
  [1940] = 1,
    ACTIONS(280), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [1945] = 1,
    ACTIONS(282), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [1950] = 2,
    ACTIONS(284), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(286), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [1957] = 1,
    ACTIONS(288), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [1962] = 2,
    ACTIONS(290), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(292), 1,
      anon_sym_LBRACE_PERCENT_DASH,
  [1969] = 2,
    ACTIONS(294), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(296), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [1976] = 2,
    ACTIONS(298), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(300), 1,
      anon_sym_LBRACE_PERCENT_DASH,
  [1983] = 1,
    ACTIONS(302), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [1988] = 2,
    ACTIONS(304), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(306), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [1995] = 2,
    ACTIONS(308), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(310), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [2002] = 2,
    ACTIONS(312), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(314), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [2009] = 2,
    ACTIONS(316), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(318), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [2016] = 1,
    ACTIONS(320), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [2021] = 1,
    ACTIONS(322), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [2026] = 2,
    ACTIONS(324), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(326), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [2033] = 1,
    ACTIONS(128), 2,
      anon_sym_PERCENT_RBRACE,
      anon_sym_DASH_PERCENT_RBRACE,
  [2038] = 2,
    ACTIONS(328), 1,
      anon_sym_PERCENT_RBRACE,
    ACTIONS(330), 1,
      anon_sym_DASH_PERCENT_RBRACE,
  [2045] = 1,
    ACTIONS(332), 1,
      anon_sym_endif,
  [2049] = 1,
    ACTIONS(334), 1,
      anon_sym_SQUOTE,
  [2053] = 1,
    ACTIONS(336), 1,
      anon_sym_endif,
  [2057] = 1,
    ACTIONS(334), 1,
      anon_sym_DQUOTE,
  [2061] = 1,
    ACTIONS(338), 1,
      anon_sym_EQ,
  [2065] = 1,
    ACTIONS(340), 1,
      sym_identifier,
  [2069] = 1,
    ACTIONS(342), 1,
      anon_sym_RBRACK,
  [2073] = 1,
    ACTIONS(344), 1,
      anon_sym_endif,
  [2077] = 1,
    ACTIONS(346), 1,
      anon_sym_endif,
  [2081] = 1,
    ACTIONS(348), 1,
      aux_sym_string_token1,
  [2085] = 1,
    ACTIONS(350), 1,
      anon_sym_endif,
  [2089] = 1,
    ACTIONS(352), 1,
      aux_sym_string_token2,
  [2093] = 1,
    ACTIONS(354), 1,
      sym_identifier,
  [2097] = 1,
    ACTIONS(356), 1,
      anon_sym_endif,
  [2101] = 1,
    ACTIONS(358), 1,
      sym_identifier,
  [2105] = 1,
    ACTIONS(360), 1,
      ts_builtin_sym_end,
  [2109] = 1,
    ACTIONS(258), 1,
      anon_sym_elseif,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 112,
  [SMALL_STATE(5)] = 162,
  [SMALL_STATE(6)] = 212,
  [SMALL_STATE(7)] = 259,
  [SMALL_STATE(8)] = 300,
  [SMALL_STATE(9)] = 335,
  [SMALL_STATE(10)] = 370,
  [SMALL_STATE(11)] = 405,
  [SMALL_STATE(12)] = 440,
  [SMALL_STATE(13)] = 475,
  [SMALL_STATE(14)] = 510,
  [SMALL_STATE(15)] = 538,
  [SMALL_STATE(16)] = 566,
  [SMALL_STATE(17)] = 594,
  [SMALL_STATE(18)] = 622,
  [SMALL_STATE(19)] = 645,
  [SMALL_STATE(20)] = 670,
  [SMALL_STATE(21)] = 691,
  [SMALL_STATE(22)] = 722,
  [SMALL_STATE(23)] = 753,
  [SMALL_STATE(24)] = 780,
  [SMALL_STATE(25)] = 805,
  [SMALL_STATE(26)] = 830,
  [SMALL_STATE(27)] = 851,
  [SMALL_STATE(28)] = 872,
  [SMALL_STATE(29)] = 894,
  [SMALL_STATE(30)] = 914,
  [SMALL_STATE(31)] = 934,
  [SMALL_STATE(32)] = 954,
  [SMALL_STATE(33)] = 974,
  [SMALL_STATE(34)] = 1003,
  [SMALL_STATE(35)] = 1022,
  [SMALL_STATE(36)] = 1051,
  [SMALL_STATE(37)] = 1070,
  [SMALL_STATE(38)] = 1099,
  [SMALL_STATE(39)] = 1128,
  [SMALL_STATE(40)] = 1157,
  [SMALL_STATE(41)] = 1176,
  [SMALL_STATE(42)] = 1208,
  [SMALL_STATE(43)] = 1240,
  [SMALL_STATE(44)] = 1267,
  [SMALL_STATE(45)] = 1293,
  [SMALL_STATE(46)] = 1317,
  [SMALL_STATE(47)] = 1343,
  [SMALL_STATE(48)] = 1366,
  [SMALL_STATE(49)] = 1389,
  [SMALL_STATE(50)] = 1412,
  [SMALL_STATE(51)] = 1435,
  [SMALL_STATE(52)] = 1458,
  [SMALL_STATE(53)] = 1481,
  [SMALL_STATE(54)] = 1504,
  [SMALL_STATE(55)] = 1517,
  [SMALL_STATE(56)] = 1530,
  [SMALL_STATE(57)] = 1541,
  [SMALL_STATE(58)] = 1552,
  [SMALL_STATE(59)] = 1563,
  [SMALL_STATE(60)] = 1574,
  [SMALL_STATE(61)] = 1585,
  [SMALL_STATE(62)] = 1596,
  [SMALL_STATE(63)] = 1607,
  [SMALL_STATE(64)] = 1618,
  [SMALL_STATE(65)] = 1629,
  [SMALL_STATE(66)] = 1640,
  [SMALL_STATE(67)] = 1651,
  [SMALL_STATE(68)] = 1662,
  [SMALL_STATE(69)] = 1673,
  [SMALL_STATE(70)] = 1684,
  [SMALL_STATE(71)] = 1695,
  [SMALL_STATE(72)] = 1706,
  [SMALL_STATE(73)] = 1717,
  [SMALL_STATE(74)] = 1728,
  [SMALL_STATE(75)] = 1739,
  [SMALL_STATE(76)] = 1750,
  [SMALL_STATE(77)] = 1761,
  [SMALL_STATE(78)] = 1772,
  [SMALL_STATE(79)] = 1783,
  [SMALL_STATE(80)] = 1794,
  [SMALL_STATE(81)] = 1810,
  [SMALL_STATE(82)] = 1826,
  [SMALL_STATE(83)] = 1839,
  [SMALL_STATE(84)] = 1849,
  [SMALL_STATE(85)] = 1859,
  [SMALL_STATE(86)] = 1869,
  [SMALL_STATE(87)] = 1879,
  [SMALL_STATE(88)] = 1889,
  [SMALL_STATE(89)] = 1899,
  [SMALL_STATE(90)] = 1909,
  [SMALL_STATE(91)] = 1916,
  [SMALL_STATE(92)] = 1921,
  [SMALL_STATE(93)] = 1928,
  [SMALL_STATE(94)] = 1933,
  [SMALL_STATE(95)] = 1940,
  [SMALL_STATE(96)] = 1945,
  [SMALL_STATE(97)] = 1950,
  [SMALL_STATE(98)] = 1957,
  [SMALL_STATE(99)] = 1962,
  [SMALL_STATE(100)] = 1969,
  [SMALL_STATE(101)] = 1976,
  [SMALL_STATE(102)] = 1983,
  [SMALL_STATE(103)] = 1988,
  [SMALL_STATE(104)] = 1995,
  [SMALL_STATE(105)] = 2002,
  [SMALL_STATE(106)] = 2009,
  [SMALL_STATE(107)] = 2016,
  [SMALL_STATE(108)] = 2021,
  [SMALL_STATE(109)] = 2026,
  [SMALL_STATE(110)] = 2033,
  [SMALL_STATE(111)] = 2038,
  [SMALL_STATE(112)] = 2045,
  [SMALL_STATE(113)] = 2049,
  [SMALL_STATE(114)] = 2053,
  [SMALL_STATE(115)] = 2057,
  [SMALL_STATE(116)] = 2061,
  [SMALL_STATE(117)] = 2065,
  [SMALL_STATE(118)] = 2069,
  [SMALL_STATE(119)] = 2073,
  [SMALL_STATE(120)] = 2077,
  [SMALL_STATE(121)] = 2081,
  [SMALL_STATE(122)] = 2085,
  [SMALL_STATE(123)] = 2089,
  [SMALL_STATE(124)] = 2093,
  [SMALL_STATE(125)] = 2097,
  [SMALL_STATE(126)] = 2101,
  [SMALL_STATE(127)] = 2105,
  [SMALL_STATE(128)] = 2109,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5), SHIFT_REPEAT(117),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5), SHIFT_REPEAT(88),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_access, 2, .production_id = 1),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_access, 2, .production_id = 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_argument_list_repeat1, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 3, .production_id = 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_access_repeat1, 3, .production_id = 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, .production_id = 8),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 7),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2), SHIFT_REPEAT(45),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 4),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_access_repeat1, 2, .production_id = 4),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 3, .production_id = 6),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter, 3, .production_id = 6),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 3, .production_id = 12),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 3, .production_id = 12),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_render_expression, 2, .production_id = 3),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_render_expression, 2, .production_id = 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter, 5, .production_id = 6),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter, 5, .production_id = 6),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_expression, 2, .production_id = 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_expression, 2, .production_id = 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(7),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(7),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(6),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(78),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_expression, 4, .production_id = 11),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elseif_expression, 5, .production_id = 13),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_expression, 3),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_expression, 4, .production_id = 14),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_operator, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_operator, 1),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparision_operator, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparision_operator, 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 7, .production_id = 11),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 7, .production_id = 11),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 8, .production_id = 16),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 8, .production_id = 16),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_expression, 8, .production_id = 13),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_expression, 8, .production_id = 13),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 10, .production_id = 20),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 10, .production_id = 20),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 9, .production_id = 19),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 9, .production_id = 19),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 3),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 9, .production_id = 18),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 9, .production_id = 18),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 8, .production_id = 15),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 8, .production_id = 15),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 8, .production_id = 13),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 8, .production_id = 13),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 9, .production_id = 17),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 9, .production_id = 17),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_expression, 7, .production_id = 11),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_expression, 7, .production_id = 11),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [250] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_expression_repeat1, 2, .production_id = 10), SHIFT_REPEAT(128),
  [253] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 2, .production_id = 10), SHIFT_REPEAT(128),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_if_expression_repeat1, 1, .production_id = 9),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_expression_repeat1, 1, .production_id = 9),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [360] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_liquid(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
